In [2]:
list=[5461,56465,698412]

In [4]:
list

[5461, 56465, 698412]

In [5]:
#2 TYPES OF ARRAYS:

#1- ARRAY ARRAYS- BUILT INTO THE CORE OF PYTHON
#2- NUMPY ARRAYS- PACKAGE THAT YOU INCLUDE IN MOST CODES

---

In [6]:
import numpy as np #when you type 'as np' it just tells python that you are calling numpy, np and you dont have to keep retyping numpy

In [7]:
import numpy as np

In [8]:
np.array(list)

array([  5461,  56465, 698412])

In [11]:
a=np.array(list)

In [12]:
a

array([  5461,  56465, 698412])

---

In [13]:
#YOU CANT HAVE DIFFERENT ELEMENTS IN ARRAYS, THEY HAVE TO BE ALL THE SAME THING
#WHEN WE CREATED LISTS, WE HAVE HAVE LETTERS, NUMBERS, AND WORDS. IN ARRAYS, IT HAS TO BE ALL THE SAME THING

---

In [15]:
a.mean()

253446.0

---

In [18]:
#SLICING ARRAYS - cant copy arrays, have to retype every time, unless you do a.copy()

In [25]:
list=[56545,5465,789,8952,2654,36541,5103]

In [26]:
np.array(list)

array([56545,  5465,   789,  8952,  2654, 36541,  5103])